name: 'Sync Markdown with Supabase'

on:
  push:
    branches: [main]

jobs:
  sync-md-with-supabase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jmagrippis/markdown-to-supabase@v0.1.6
        with:
          supabase-url: ${{ vars.PUBLIC_SUPABASE_URL }}
          supabase-service-role-key: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          docs-root-path: 'docs/videos'
          target-table: 'videos'
