name: Playwright Tests

on: [deployment_status]

jobs:
  test:
    if: github.event.deployment_status.state == 'success'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Install Playwright Browsers
        run: bunx playwright install --with-deps
      - name: Run Playwright tests against ${{ github.event.deployment_status.target_url }}
        run: bun run test:e2e
        env:
          PUBLIC_ROOT_URL: ${{ github.event.deployment_status.target_url }}
          PLAYWRIGHT_LOGGED_IN_PASSWORD: ${{ secrets.PLAYWRIGHT_LOGGED_IN_PASSWORD }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 30
